export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const CREATE_GLOBAL_NOTIFICATION = 'CREATE_GLOBAL_NOTIFICATION';
export const REMOVE_GLOBAL_NOTIFICATION = 'REMOVE_GLOBAL_NOTIFICATION';
export const CREATE_OBJECT_WARNING = 'CREATE_OBJECT_WARNING';
