export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const CREATE_GLOBAL_NOTIFICATION = 'CREATE_GLOBAL_NOTIFICATION';
export const REMOVE_GLOBAL_NOTIFICATION = 'REMOVE_GLOBAL_NOTIFICATION';
export const DISPLAY_NOTIFICATION_WARNING = 'DISPLAY_NOTIFICATION_WARNING';
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS';
