load_berks_file($WORKSPACE_SETTINGS[:ecosystem][:root][:chef][:berksfile])


cookbook_from_git 'chef_commons', '2.0.0'
cookbook_from_git 'extras', '0.1.70'
cookbook_from_git 'maven', '1.0.0'

cookbook_from_git 'jdk_linux','11.0.19'
cookbook_from_git 'jdk_windows','11.0.19'
cookbook_from_git 'jdk_mac','11.0.19'
cookbook 'java', '~> 10.0.0'

cookbook_from_github 'mstr-ecosystem-cookbooks', 'nodejs','18.16.0'

cookbook 'seven_zip', '~> 2.0.0'
cookbook_from_git 'docker', '0.1.33'
