load_berks_file($WORKSPACE_SETTINGS[:ecosystem][:root][:chef][:berksfile])


cookbook_from_git 'chef_commons', '2.0.0'
cookbook_from_git 'extras', '0.1.70'
cookbook_from_git 'maven', '1.0.0'

cookbook_from_git 'java-osx', '0.1.1'
cookbook_from_git 'java-windows', '1.0.3'
cookbook_from_git 'java_ecosystem', '0.1.66'
cookbook_from_github 'mstr-ecosystem-cookbooks', 'nodejs','16.19.1'

cookbook 'java', '4.3.0'

cookbook 'seven_zip', '~> 2.0.0'
cookbook_from_git 'docker', '0.1.33'
