load_berks_file($WORKSPACE_SETTINGS[:ecosystem][:root][:chef][:berksfile])


cookbook_from_git 'chef_commons', '1.1.13'
cookbook_from_git 'extras', '0.1.61'
cookbook_from_git 'nodejs', '0.1.1'

cookbook_from_git 'java-osx', '0.1.1'
cookbook_from_git 'java-windows', '1.0.3'
cookbook_from_git 'virtualbox', '0.8.11'

cookbook 'java'

cookbook 'seven_zip', '~> 2.0.0'
