DRIVER_TYPE_WINDOWS_DESKTOP = 'windows_desktop'
DRIVER_TYPE_WINDOWS_CHROME = 'windows_chrome'
DRIVER_TYPE_MAC_DESKTOP = 'mac_desktop'
DRIVER_TYPE_MAC_CHROME = 'mac_chrome'

AVAILABLE_DRIVERS = [
    DRIVER_TYPE_WINDOWS_DESKTOP,
    DRIVER_TYPE_WINDOWS_CHROME,
    DRIVER_TYPE_MAC_DESKTOP,
    DRIVER_TYPE_MAC_CHROME
]
