export const MODIFY_OBJECT = 'MODIFY_OBJECT';
export const REFRESH_STORED_OBJECT = 'REFRESH_STORED_OBJECT';
export const GET_INSTANCE_DEFINITION = 'GET_INSTANCE_DEFINITION';
export const GET_OFFICE_TABLE_IMPORT = 'GET_OFFICE_TABLE_IMPORT';
export const GET_OFFICE_TABLE_EDIT_REFRESH = 'GET_OFFICE_TABLE_EDIT_REFRESH';
export const FORMAT_DATA = 'FORMAT_DATA';
export const FETCH_INSERT_DATA = 'FETCH_INSERT_DATA';
export const FORMAT_OFFICE_TABLE = 'FORMAT_OFFICE_TABLE';
export const FORMAT_SUBTOTALS = 'FORMAT_SUBTOTALS';
export const BIND_OFFICE_TABLE = 'BIND_OFFICE_TABLE';
export const SAVE_OBJECT_IN_EXCEL = 'SAVE_OBJECT_IN_EXCEL';

export const IMPORT_OPERATION = 'IMPORT_OPERATION';
export const EDIT_OPERATION = 'EDIT_OPERATION';
export const REFRESH_OPERATION = 'REFRESH_OPERATION';

export const operationStepsMap = {
  IMPORT_OPERATION: [
    GET_INSTANCE_DEFINITION,
    GET_OFFICE_TABLE_IMPORT,
    FORMAT_DATA,
    FETCH_INSERT_DATA,
    FORMAT_OFFICE_TABLE,
    FORMAT_SUBTOTALS,
    BIND_OFFICE_TABLE,
    SAVE_OBJECT_IN_EXCEL,
  ],

  REFRESH_OPERATION: [
    GET_INSTANCE_DEFINITION,
    GET_OFFICE_TABLE_EDIT_REFRESH,
    FORMAT_DATA,
    FETCH_INSERT_DATA,
    FORMAT_OFFICE_TABLE,
    FORMAT_SUBTOTALS,
    BIND_OFFICE_TABLE,
    SAVE_OBJECT_IN_EXCEL,
  ],

  EDIT_OPERATION: [
    MODIFY_OBJECT,
    GET_INSTANCE_DEFINITION,
    GET_OFFICE_TABLE_EDIT_REFRESH,
    FORMAT_DATA,
    FETCH_INSERT_DATA,
    FORMAT_OFFICE_TABLE,
    FORMAT_SUBTOTALS,
    BIND_OFFICE_TABLE,
    SAVE_OBJECT_IN_EXCEL,
  ],
};
