DEFAULT_TIMEOUT = 60
DEFAULT_IMAGE_TIMEOUT = 10
DEFAULT_WAIT_BETWEEN_CHECKS = 0.4
DEFAULT_WAIT_AFTER_SEND_KEY = 0.5
SHORT_TIMEOUT = 3
MEDIUM_TIMEOUT = 10
LONG_TIMEOUT = 180

ELEMENT_SEARCH_RETRY_NUMBER = 20
ELEMENT_SEARCH_RETRY_INTERVAL = 2
SEND_KEYS_RETRY_NUMBER = 10
AFTER_OPERATION_WAIT_TIME = 1

DEFAULT_LOCALE_NAME = 'en-us'

TUTORIAL_PROJECT_ID = 'B7CA92F04B9FAE8D941C3E9B7E0CD754'
